Repository Wopslang/Wops, pull requests merged in 2022-01, with the labels that each got.

#45 Stability Improvement
  .github/workflows/ubuntu.yml
  .github/workflows/wopslang-ci.yml
  Makefile
  README.md
  build.sh
  sample/fizzbuzz.wops
  sample/hailstone_sequence.wops
  src/runtime/AST.h
  test/ci-test.wops
Labels: bug, enhancement

#46 Fixed reported bug #44
  .github/workflows/windows.yml
  README.md
Labels: bug, enhancement

#47 added howto.md
  doc/howto.md
Labels: documentation

#49 v0.1.4
  CHANGELOG
  README.md
  build.sh
  src/error/signal.h
  src/import_/eexec_.cpp
  src/interpreter.cpp
  src/parser/parse.cpp
  src/parser/parse.h
  src/runtime/AST.h
  src/type/variable.h
Labels: release
